### ISSUE TITLE
Parsing Wring Input Output after Codeforces site updation

### ISSUE THREAD

**Issue by khokharnikunj8** [jmerle/chelper-companion#1]
Extension is parsing wrong input output data after updation of codeforces site updation by adding copy button. @jmerle

**Comment by jmerle** [comment]
That's a bug, I'll get right on it. Thanks for letting me know.

**Comment by jmerle** [comment]
I fixed the issue and deployed a new version. It's currently in the reviewing stage, so it might take a few hours before you can see it. Unless you've changed it, browsers normally automatically update extensions, so expect it working in about 24 hours.
