### ISSUE TITLE
The parser is not working in my case.

### ISSUE THREAD

**Issue by CuriousNikhil** [jmerle/chelper-companion#2]
When I try to click on the extension + icon, it just doesn't show up. Not a pop up nor eventlog nothing.
Please help me. I have installed CHelper plugin on intellJ. Thanks in advanced.

**Comment by jmerle** [comment]
On which website (a specific url would be useful) are you trying to use CHelper Companion?

**Comment by CuriousNikhil** [comment]
I am using it on Codechef. 
Actually, I was trying to fix this problem. So, I just removed plugin and installed from store again. It's working flawless!! Thanks for this one !!
