### ISSUE TITLE
Fails to read HackerRank multiple test cases

### ISSUE THREAD

**Issue by tgvdinesh** [jmerle/chelper-companion#4]
[Hacker Rank - 30-conditional-statements/problem](https://www.hackerrank.com/challenges/30-conditional-statements/problem)

```
{
  "group": "",
  "input": {
    "type": "stdin"
  },
  "languages": {
    "java": {
      "mainClass": "Main",
      "taskClass": "HackerRankTutorials30DaysOfCode"
    }
  },
  "memoryLimit": 512,
  "name": "HackerRank - Tutorials - 30 Days of Code",
  "output": {
    "type": "stdout"
  },
  "testType": "single",
  *"tests": []*,
  "timeLimit": 4000,
  "url": "https://www.hackerrank.com/challenges/30-conditional-statements/problem"
}
```

As the result provided above shows, it doesn't parse multiple test cases. This is because of css query used in HackerRank Parser.

I guess ```[class*="challenge-body-html"] pre``` query should work.

**Comment by jmerle** [comment]
Thanks. The test output is fixed, the group and the name will be fixed very soon.
